version: '3'
services:
  # http://localhost:8086/signin
  # Create an organization named "factorialhr"
  # Create a bucket named "iot"
  # Create a token going to "Data (Load Data) > API Tokens"
  influxdb:
    image: influxdb:2.7.4-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_USER=myuser
      - INFLUXDB_USER_PASSWORD=mypassword
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
    volumes:
      - ./:/var/lib/influxdb